language: c

os: linux
dist: bionic

# don't build tags separately
if: tag IS blank

compiler: gcc

cache: ccache

before_install:
  - travis_retry ./scripts/test.sh deps
  - travis_retry ./scripts/test.sh pydeps

before_script:
  - sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0 || true

script:
  - ./scripts/test.sh

after_success:
  if [ "$TEST" == "coverage" ]; then
    bash <(curl -s https://codecov.io/bash);
  fi

after_failure:
  - cat config.log
  - sleep 1

env:
  global:
    - TESTS_REDUCED_KEYLENGTHS=yes
    - LEAK_DETECTIVE=no
    - MONOLITHIC=no

jobs:
  include:
    - env: TEST=sonarcloud
      if: type = push AND env(SONAR_TOKEN) IS present
      git:
        depth: false
      cache:
        directories:
          - $HOME/.sonar-cache
      addons:
        sonarcloud:
          organization: "ryru"
    - env: TEST=sonarcloud
      if: type = push AND env(SONAR_TOKEN) IS present
      arch: arm64-graviton2
      virt: lxd
      group: edge
      git:
        depth: false
      cache:
        directories:
          - $HOME/.sonar-cache
      addons:
        sonarcloud:
          organization: "ryru"
    - env: TEST=lgtm
      if: type = push AND env(LGTM_TOKEN) IS present
      git:
        depth: false
    - env: TEST=lgtm
      if: type = push AND env(LGTM_TOKEN) IS present
      arch: arm64-graviton2
      virt: lxd
      group: edge
      git:
        depth: false
    - env: TEST=all
    - env: TEST=all
      arch: arm64-graviton2
      virt: lxd
      group: edge
    - env: TEST=all
      compiler: clang
    - env: TEST=all
      compiler: clang
      arch: arm64-graviton2
      virt: lxd
      group: edge
    - env: TEST=all
      dist: xenial
    - env: TEST=all
      dist: xenial
      arch: arm64-graviton2
      virt: lxd
      group: edge
    - env: TEST=all
      dist: xenial
      compiler: clang
    - env: TEST=all
      dist: xenial
      compiler: clang
      arch: arm64-graviton2
      virt: lxd
      group: edge
